import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        maxWidth: 343,
        padding: 15,
        alignItems: "center",
        gap: 16,
        borderWidth: 1,
        borderRadius: 10,
        borderColor: "#CDCED2",
        backgroundColor: "white",
    },
    profileContainer: {
        position: "relative",
        marginTop: 15,
    },
    imageOnline: {
        position: "absolute",
        width: 20,
        height: 20,
        borderWidth: 2,
        borderColor: "white",
        bottom: 0,
        right: 0,
    },
    profileImage: {
        width: 96,
        height: 96,
        borderRadius: 360,
    },
    textContainer: {
        justifyContent: "center",
        gap: 10,
    },
    nameText: {
        fontSize: 24,
        fontWeight: "700",
        textAlign: "center",
        color: "#070A1C",
    },
    usernameText: {
        fontSize: 16,
        fontWeight: "500",
        color: "#070A1C",
        textAlign: "center",
    },
    buttonsContainer: {
        flexDirection: "row",
        gap: 16,
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
    },
    confirmButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#543C52",
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 1234,
        gap: 8,
        minWidth: 111,
    },
    deleteButton: {
        backgroundColor: "transparent",
        borderRadius: 1234,
        minWidth: 111,
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: "#543C52",
        alignItems: "center",
        justifyContent: "center",
    },
    buttonText: {
        color: "white",
        fontSize: 14,
        fontWeight: "500",
    },
    buttonDeleteText: {
        color: "#543C52",
        fontSize: 14,
        fontWeight: "500",
    },
});
